export const programmingLanguagesList = [
  "Next Js",
  "Python",
  "Flutter",
  "C++",
  "Vue",
  "Typescript",
  "Javascript",
  "React",
  "Angular",
  "React Native",
  "PHP",
  "Node.Js",
  "MongoDB",
  "Express",
  "Sql",
];

export const difficultyLevels = ["Newbie", "Junior", "Intermediate", "Advanced", "Guru"];

export const projectCategories = [
  "Web Development",
  "Mobile Development",
  "Data Science",
  "Machine Learning",
  "Artificial Intelligence",
  "Blockchain",
  "DevOps",
  "Cloud Computing",
  "Cybersecurity",
  "Game Development",
  "IoT",
  "AR/VR",
  "3D Graphics",
  "Robotics",
  "Natural Language Processing",
  "Computer Vision",
  "Embedded Systems",
  "Quantum Computing",
  "Augmented Reality",
  "Virtual Reality",
  "Blockchain",
  "Cryptocurrency",
  "Smart Contracts",
  "Decentralized Finance (DeFi)",
  "Artificial Intelligence",
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing",
  "Computer Vision",
  "Robotics",
  "IoT",
  "AR/VR",
  "3D Graphics",
  "Embedded Systems",
  "Quantum Computing",
  "Augmented Reality",
  "Virtual Reality",
  "Blockchain",
  "Cryptocurrency",
  "Smart Contracts",
];

export const sortBy = ["Most Recent", "Difficulty (easier first)", "Difficulty (harder first)"];

export const projects = [
  {
    id: 1,
    name: "Project Alpha",
    description: "A cutting-edge web framework for building scalable applications.",
    language: "JavaScript",
    category: "Web Development",
    difficulty: "Intermediate",
    stars: 1200,
    forks: 350,
    watchers: 80,
    githubUrl: "https://github.com/contribhub/project-alpha",
    createdAt: "2023-01-15",
    updatedAt: "2024-03-10",
    license: "MIT",
    readme:
      "# Project Alpha\n\nProject Alpha is a cutting-edge web framework designed for building scalable applications. It provides developers with a robust set of tools and features to streamline the development process and create high-performance web applications.\n\n## Features\n\n- Fast rendering engine\n- Built-in state management\n- Server-side rendering support\n- Extensible plugin system\n\n## Getting Started\n\nTo get started with Project Alpha, follow these steps:\n\n1. Install the framework: `npm install project-alpha`\n2. Create a new project: `npx create-project-alpha my-app`\n3. Navigate to your project: `cd my-app`\n4. Start the development server: `npm run dev`\n\n## Documentation\n\nFor full documentation, visit our [official docs](https://projectalpha.dev/docs).\n\n## Contributing\n\nWe welcome contributions! Please see our [contributing guide](CONTRIBUTING.md) for more details.",
    issues: [
      { id: 1, title: "Improve error handling in API requests", status: "open" },
      { id: 2, title: "Add support for custom themes", status: "open" },
      { id: 3, title: "Optimize bundle size for better performance", status: "open" },
    ],
    pullRequests: [
      { id: 1, title: "Fix typo in documentation", status: "open" },
      { id: 2, title: "Add new utility functions", status: "merged" },
      { id: 3, title: "Implement dark mode support", status: "open" },
    ],
  },
  {
    id: 2,
    name: "Data Cruncher",
    description: "High-performance data processing library for big data applications.",
    language: "Python",
    category: "Data Science",
    difficulty: "Advanced",
    stars: 890,
    forks: 210,
    watchers: 65,
    githubUrl: "https://github.com/contribhub/data-cruncher",
    createdAt: "2023-03-22",
    updatedAt: "2024-02-28",
    license: "Apache 2.0",
    readme:
      "# Data Cruncher\n\nData Cruncher is a high-performance data processing library designed for big data applications. It provides efficient algorithms and data structures to handle large-scale data processing tasks.\n\n## Features\n\n- Fast data parsing and transformation\n- Distributed computing support\n- Advanced data visualization tools\n- Machine learning integration\n\n## Installation\n\nInstall Data Cruncher using pip:\n\n```\npip install data-cruncher\n```\n\n## Usage\n\n```python\nfrom data_cruncher import DataProcessor\n\nprocessor = DataProcessor()\nresult = processor.analyze('large_dataset.csv')\nprint(result.summary())\n```\n\n## Documentation\n\nFor full documentation, visit our [official docs](https://datacruncher.dev/docs).\n\n## Contributing\n\nContributions are welcome! Please read our [contributing guidelines](CONTRIBUTING.md) before submitting a pull request.",
    issues: [
      { id: 1, title: "Add support for streaming data processing", status: "open" },
      { id: 2, title: "Improve memory efficiency for large datasets", status: "open" },
      { id: 3, title: "Implement parallel processing for faster analysis", status: "open" },
    ],
    pullRequests: [
      { id: 1, title: "Add new data visualization module", status: "open" },
      { id: 2, title: "Optimize sorting algorithm for better performance", status: "merged" },
      { id: 3, title: "Fix bug in CSV parser", status: "open" },
    ],
  },
  {
    id: 3,
    name: "Mobile Kit",
    description: "Comprehensive toolkit for cross-platform mobile app development.",
    language: "React Native",
    category: "Mobile Development",
    difficulty: "Junior",
    stars: 2300,
    forks: 580,
    watchers: 120,
    githubUrl: "https://github.com/contribhub/mobile-kit",
    createdAt: "2023-05-10",
    updatedAt: "2024-03-15",
    license: "MIT",
    readme:
      "# Mobile Kit\n\nMobile Kit is a comprehensive toolkit for cross-platform mobile app development. It provides a set of pre-built components and utilities to accelerate the development of high-quality mobile applications.\n\n## Features\n\n- Cross-platform compatibility (iOS and Android)\n- Pre-built UI components\n- State management solutions\n- Native module integration\n\n## Getting Started\n\n1. Install the Mobile Kit CLI:\n   ```\n   npm install -g mobile-kit-cli\n   ```\n2. Create a new project:\n   ```\n   mobile-kit create MyAwesomeApp\n   ```\n3. Navigate to your project directory:\n   ```\n   cd MyAwesomeApp\n   ```\n4. Start the development server:\n   ```\n   npm start\n   ```\n\n## Documentation\n\nFor full documentation and guides, visit our [official documentation](https://mobilekit.dev/docs).\n\n## Contributing\n\nWe welcome contributions from the community! Please read our [contributing guidelines](CONTRIBUTING.md) before submitting a pull request.",
    issues: [
      { id: 1, title: "Add support for Flutter integration", status: "open" },
      { id: 2, title: "Improve accessibility features", status: "open" },
      { id: 3, title: "Implement offline mode for better user experience", status: "open" },
    ],
    pullRequests: [
      { id: 1, title: "Add new animation components", status: "open" },
      { id: 2, title: "Optimize image loading for better performance", status: "merged" },
      { id: 3, title: "Fix layout issues on smaller devices", status: "open" },
    ],
  },
];
