export const programmingLanguagesList = [
  "Next Js",
  "Python",
  "Flutter",
  "C++",
  "Vue",
  "Typescript",
  "Javascript",
  "React",
  "Angular",
  "React Native",
  "PHP",
  "Node.Js",
  "MongoDB",
  "Express",
  "Sql",
];

export const difficultyLevels = ["Newbie", "Junior", "Intermediate", "Advanced", "Guru"];

export const projectCategories = [
  "Web Development",
  "Mobile Development",
  "Data Science",
  "Machine Learning",
  "Artificial Intelligence",
  "Blockchain",
  "DevOps",
  "Cloud Computing",
  "Cybersecurity",
  "Game Development",
  "IoT",
  "AR/VR",
  "3D Graphics",
  "Robotics",
  "Natural Language Processing",
  "Computer Vision",
  "Embedded Systems",
  "Quantum Computing",
  "Augmented Reality",
  "Virtual Reality",
  "Blockchain",
  "Cryptocurrency",
  "Smart Contracts",
  "Decentralized Finance (DeFi)",
  "Artificial Intelligence",
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing",
  "Computer Vision",
  "Robotics",
  "IoT",
  "AR/VR",
  "3D Graphics",
  "Embedded Systems",
  "Quantum Computing",
  "Augmented Reality",
  "Virtual Reality",
  "Blockchain",
  "Cryptocurrency",
  "Smart Contracts",
];

export const sortBy = ["Most Recent", "Difficulty (easier first)", "Difficulty (harder first)"];

export const projects = [
  {
    id: 1,
    name: "Project Alpha",
    description: "A cutting-edge web framework for building scalable applications.",
    language: "JavaScript",
    category: "Web Development",
    difficulty: "Intermediate",
  },
  {
    id: 2,
    name: "Data Cruncher",
    description: "High-performance data processing library for big data applications.",
    language: "Python",
    category: "Data Science",
    difficulty: "Advanced",
  },
  {
    id: 3,
    name: "Mobile Kit",
    description: "Comprehensive toolkit for cross-platform mobile app development.",
    language: "React Native",
    category: "Mobile Development",
    difficulty: "Junior",
  },
  {
    id: 4,
    name: "AI Assistant",
    description: "Advanced AI model for natural language processing and generation.",
    language: "Python",
    category: "Artificial Intelligence",
    difficulty: "Guru",
  },
  {
    id: 5,
    name: "Secure Auth",
    description: "Robust authentication and authorization system for web applications.",
    language: "Typescript",
    category: "Web Development",
    difficulty: "Intermediate",
  },
  {
    id: 6,
    name: "Cloud Manager",
    description: "Simplified cloud infrastructure management and deployment tool.",
    language: "Go",
    category: "DevOps",
    difficulty: "Advanced",
  },
  {
    id: 7,
    name: "Game Engine",
    description: "Feature-rich game engine for creating immersive gaming experiences.",
    language: "C++",
    category: "Game Development",
    difficulty: "Guru",
  },
  {
    id: 8,
    name: "AR/VR Toolkit",
    description: "Tools for creating immersive AR and VR experiences.",
    language: "C++",
    category: "AR/VR",
    difficulty: "Intermediate",
  },
  {
    id: 9,
    name: "Blockchain Explorer",
    description: "User-friendly blockchain explorer for tracking transactions.",
    language: "Typescript",
    category: "Blockchain",
    difficulty: "Junior",
  },
  {
    id: 10,
    name: "AI Chatbot",
    description: "Intelligent chatbot powered by advanced AI models.",
    language: "Python",
    category: "Artificial Intelligence",
    difficulty: "Advanced",
  },
];
